services:
  # api:
  #   container_name: service-api
  #   build:
  #     context: .
  #   environment:
  #     DATABASE_URL: "postgresql://${DATABASE_USER:-pharminc}:${DATABASE_PASSWORD}@database:5432/${DATABASE_DB:-pharminc}?schema=public"
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.api.rule=Host(`${API_HOST:-api.pharminc.in}`)"
  #   ports:
  #     - "3001:3000"

  database:
    container_name: pharminc-database
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER:-pharminc}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB:-pharminc}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
    driver: local
